name: Timer
main: ch.thejucon.timer.Start
version: 1.0
api-version: 1.20
description: A Minecraft timer with start, pause and stop
commands:
  timer:
    description: Kontrolliert den Timer
    usage: /timer <start|stop|pause|settime>
    aliases: [time]